ALTER TABLE [dbo].[PersonName]
    ADD CONSTRAINT [PK_PersonName] PRIMARY KEY CLUSTERED ([NameId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

